server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: 192.168.81.129:9200
  rabbitmq:
    host: 192.168.81.129
    virtual-host: /lijing
    username: lijing
    password: lijing