server:
  port: 8093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
  redis:
    host: 192.168.81.129
  rabbitmq:
    host: 192.168.81.129
    port: 5672
    virtual-host: /lijing
    username: lijing
    password: lijing
jwt:
  token:
    pubKeyPath: E:\jwt\rsa.pub
    cookieName: gmall-token
    userKey: user-key
    expireTime: 7776000

#http://gmalllmj.free.idcfengye.com
alipay:
  app_id: 2016101200666477
  notify_url: http://gmalllmj.free.idcfengye.com/pay/success #支付宝异步调用 路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html   #支付宝同步调用
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do  #支付宝网关