spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.81.129
  rabbitmq:
    host: 192.168.81.129
    virtual-host: /lijing
    username: lijing
    password: lijing
    port: 5672
jwt:
  token:
    pubKeyPath: E:\jwt\rsa.pub
    cookieName: gmall-token
    userKey: user-key
    expireTime: 7776000
server:
  port: 8090